#!/usr/bin/expect -f

set timeout 120

proc cleanup {} {
	catch {exec pkill -f qemu-system-riscv64}
	exit 130
}

trap {cleanup} {SIGINT SIGTERM SIGHUP}

spawn make run

expect "buildroot login:"

send "root\r"

expect "Password:"

send "sifive\r"

expect "#"

send "modprobe keystone-driver\r"

expect "#"

send "/usr/share/keystone/examples/rewind.ke \r"

expect "#"

send "poweroff\r"

expect "Power down"

